server {
    listen 80;
    listen [::]:80;
    server_name eubot.seo.srl;

    root /var/www/eubot;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|ico|svg|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
